services:
  orkestra.transactor_repository:
    class: Orkestra\Transactor\Repository\TransactorRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: [ Orkestra\Transactor\Entity\TransactorBase ]
    calls:
      - [ setContainer, [ @service_container ] ]